---
- hosts: localhost
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install SDKMAN
      command: "curl -s https://get.sdkman.io | bash"

    - name: Source SDKMAN
      shell: source "$HOME/.sdkman/bin/sdkman-init.sh"

    - name: Install Grails 2.4.4
      command: "sdk install grails 2.4.4"
