---
- hosts: localhost
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install SDKMAN
      command: "curl -s https://get.sdkman.io | bash"
      register: sdkman_install_output
      ignore_errors: true

    - debug:
        msg: "{{ sdkman_install_output.stdout_lines }}"

    - name: Source SDKMAN
      shell: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
      environment:
        HOME: "{{ ansible_env.HOME }}"
      when: sdkman_install_output.rc == 0

    - name: Install Grails 2.4.4
      command: "sdk install grails 2.4.4"
      environment:
        HOME: "{{ ansible_env.HOME }}"
      when: sdkman_install_output.rc == 0


